default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: megs
  password: 0852369147
  host: localhost

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: megs
  password: 0852369147
  host: localhost

test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: megs
  password: 0852369147
  host: localhost

production:
  <<: *default
  database: production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: megs
  password: 0852369147
  host: localhost
